-- Script tạo 3 bảng HR cho hệ thống authentication
-- Bảng sy_user, hr_employee, hr_department

-- Tạo bảng sy_user
CREATE TABLE sy_user (
    USER_NO VARCHAR(20) PRIMARY KEY,
    PERSON_ID VARCHAR(20) NOT NULL,
    CPNY_ID VARCHAR(10) NOT NULL,
    USER_NAME VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    SPECIAL_PARAM VARCHAR(100),
    SPECIAL_VALUE VARCHAR(255),
    USER_TYPE VARCHAR(20),
    PASSWORD_FIRST VARCHAR(255),
    PASSWORD_SECOND VARCHAR(255),
    PASSWORD_THIRD VARCHAR(255),
    CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(50),
    UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(50),
    ORDERNO INTEGER,
    ACTIVITY INTEGER DEFAULT 1,
    PERSONAL_DATA_FLAG VARCHAR(1),
    PERSONAL_DATA_UPDATE_DATE TIMESTAMP,
    PERSONAL_DATA_UPDATED_IP VARCHAR(50),
    PERSONAL_DATA_UPDATED_BY VARCHAR(50),
    PERSONAL_SEND_DATA_FLAG VARCHAR(1),
    PERSONAL_SEND_DATA_UPDATE_DATE TIMESTAMP,
    PERSONAL_SEND_DATA_UPDATED_IP VARCHAR(50),
    PERSONAL_SEND_DATA_UPDATED_BY VARCHAR(50)
);

-- Tạo bảng hr_employee
CREATE TABLE hr_employee (
    EMPID VARCHAR(20) PRIMARY KEY,
    CHINESE_PINYIN VARCHAR(100),
    ENGLISH_NAME VARCHAR(100),
    POSITION_NO VARCHAR(20),
    POST_GRADE_NO VARCHAR(20),
    DATE_STARTED TIMESTAMP,
    END_PROBATION_DATE TIMESTAMP,
    EMP_TYPE_CODE VARCHAR(20),
    CPNY_ID VARCHAR(10) NOT NULL,
    PERSON_ID VARCHAR(20) NOT NULL,
    DEPTNO VARCHAR(20) NOT NULL,
    LOCAL_NAME VARCHAR(100),
    WORK_AREA VARCHAR(50),
    CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(50),
    UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(50),
    ACTIVITY INTEGER DEFAULT 1,
    MAIN_BUSINESS VARCHAR(100),
    EXPERIENCE VARCHAR(500),
    UPDATED_IP VARCHAR(50),
    CREATED_IP VARCHAR(50),
    KOREAN_NAME VARCHAR(100),
    EMP_COMMON_TYPE_CODE VARCHAR(20),
    STANDARD_POSITION VARCHAR(100),
    DUTY_NO VARCHAR(20),
    POST_NO VARCHAR(20),
    STATUS_CODE VARCHAR(20),
    DATE_LEFT TIMESTAMP,
    ID_CARD_NO VARCHAR(20),
    SHIFT_NO VARCHAR(20),
    EMP_OFFICE VARCHAR(100),
    INCUMBENCY VARCHAR(1),
    PROMOTION_DAY TIMESTAMP,
    POST_FAMILY VARCHAR(100),
    AFFIRM_WORK_AGE VARCHAR(20),
    WORK_HOUR_TYPE VARCHAR(20),
    DIRECT_INDIRECT_DISTINCTION VARCHAR(20),
    RECRUIT_TYPE VARCHAR(20),
    INSURANCE_TYPE VARCHAR(20),
    INSURANCE_AREA VARCHAR(50),
    FILENUMBER VARCHAR(50),
    EMPLOYEE_OWNED VARCHAR(100),
    WAGE_TYPE VARCHAR(20),
    POSITION VARCHAR(100),
    DATE_LAST_UP TIMESTAMP,
    RECOMMEND VARCHAR(100),
    DATE_GROUP_ENTRY TIMESTAMP,
    LAST_HAOFENG_DATE TIMESTAMP,
    ASSIGNMENT_INFORMATION VARCHAR(500),
    COST_CENTER VARCHAR(20),
    PAY_STEP_NO VARCHAR(20),
    PHONE_CARD_NO VARCHAR(20),
    LIZHIREASON VARCHAR(500),
    SOCIAL_DIFFERENTIATION VARCHAR(20),
    IS_PROBATION VARCHAR(1),
    PERSON_SUPPLIER_COMPANY VARCHAR(100),
    OT_LIMIT VARCHAR(20),
    OT_LIMIT_100 VARCHAR(20)
);

-- Tạo bảng hr_department
CREATE TABLE hr_department (
    DEPTID VARCHAR(20) PRIMARY KEY,
    CPNY_ID VARCHAR(10) NOT NULL,
    DATE_CREATED TIMESTAMP,
    DATE_ENDED TIMESTAMP,
    DEPT_LEVEL INTEGER,
    MANAGER_EMP_ID VARCHAR(20),
    DEPTNO VARCHAR(20) NOT NULL UNIQUE,
    PARENT_DEPT_NO VARCHAR(20),
    WORK_AREA VARCHAR(50),
    DEPT_TYPE VARCHAR(20),
    ORG_NAME_ENG VARCHAR(200),
    ORG_NAME_LOCAL VARCHAR(200),
    ORG_LEVEL VARCHAR(20),
    COST_CENTER VARCHAR(20),
    USE_YN VARCHAR(1) DEFAULT 'Y',
    CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(50),
    UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(50),
    ORDERNO INTEGER,
    ACTIVITY INTEGER DEFAULT 1,
    IS_DEPT VARCHAR(1),
    IS_PART_TIME VARCHAR(1),
    PRODUCT_TYPE VARCHAR(50),
    CREATED_IP VARCHAR(50),
    UPDATED_IP VARCHAR(50),
    RESUME_NO VARCHAR(50),
    REMARK VARCHAR(500),
    FEE_STANDARD VARCHAR(50),
    DEPT_DISTINGUISH_STANDARD VARCHAR(50),
    PREP_MANAGER_EMP_ID VARCHAR(20),
    ORDER_NO VARCHAR(20),
    ORG_NAME_KO VARCHAR(200),
    ORG_NAME_VI VARCHAR(200)
);

-- Tạo indexes để tối ưu performance
CREATE INDEX idx_sy_user_username ON sy_user(USER_NAME);
CREATE INDEX idx_sy_user_person_id ON sy_user(PERSON_ID);
CREATE INDEX idx_sy_user_cpny_id ON sy_user(CPNY_ID);

CREATE INDEX idx_hr_employee_person_id ON hr_employee(PERSON_ID);
CREATE INDEX idx_hr_employee_deptno ON hr_employee(DEPTNO);
CREATE INDEX idx_hr_employee_cpny_id ON hr_employee(CPNY_ID);
CREATE INDEX idx_hr_employee_activity ON hr_employee(ACTIVITY);

CREATE INDEX idx_hr_department_deptno ON hr_department(DEPTNO);
CREATE INDEX idx_hr_department_cpny_id ON hr_department(CPNY_ID);
CREATE INDEX idx_hr_department_parent ON hr_department(PARENT_DEPT_NO);
CREATE INDEX idx_hr_department_activity ON hr_department(ACTIVITY);

-- Tạo foreign key constraints (tùy chọn)
-- ALTER TABLE hr_employee ADD CONSTRAINT fk_hr_employee_person_id 
--     FOREIGN KEY (PERSON_ID) REFERENCES sy_user(PERSON_ID);
-- 
-- ALTER TABLE hr_employee ADD CONSTRAINT fk_hr_employee_deptno 
--     FOREIGN KEY (DEPTNO) REFERENCES hr_department(DEPTNO);
